name: Build

on: [ push, pull_request ]

jobs:
  Build:
    name: Build with PHP ${{ matrix.php }}
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php: ['8.1', '8.2']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            PHP_VERSION=${{ matrix.php }}

  Test:
    name: Test image
    needs: Build
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php: ['8.1', '8.2']
    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=-1, display_errors=On
          coverage: none
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --no-scripts --no-plugins

